### ISSUE TITLE
error right at the beginning

### ISSUE THREAD

**Issue by vblanche21** [gszep/FlowAtlas.jl#35]
Hello,
I'm getting this error:
![image](https://github.com/gszep/FlowAtlas.jl/assets/80763021/80a1de3c-9bfa-43f2-baf1-5245b9a10d2c)

What should I do?

Many thanks,
Vincent

**Comment by gszep** [comment]
Hi there! Thank you so much for submitting this bug report 😁 I am keen to get this fixed for you so that FlowAtlas may be useful to you! Would you be able to attach a small sample of the file that FlowAtlas is failing to load?

**Comment by vblanche21** [comment]
> Hi there! Thank you so much for submitting this bug report 😁 I am keen to get this fixed for you so that FlowAtlas may be useful to you! Would you be able to attach a small sample of the file that FlowAtlas is failing to load?

Hi, many thanks, Here is the FSC file. appreciate your help.

**Comment by gszep** [comment]
Hi @vblanche21 ! Apologies for the delayed progress on this. I've investigated the issue:
* The string patterns that I was using to identify channels were too relaxed and the code was accidentally parsing the `$PANELNAME` keyword as a channel.
* the channel names (property "S") were not unique; `--A` and `--H` were assigned to two different channels

I am updating `FlowWorkspace.jl` and `FlowAtlas.jl` to deal with the above issues. For now, an error is raised to ask the user to rename duplicate channel names

**Comment by gszep** [comment]
updating `FlowAtlas.jl` to use FlowWorkspace v0.1.17 and de-duplicating `--A` and `--H` for `FL5` and `FL8` will allow you to use FlowAtlas :)
